### ISSUE TITLE
TypeError: process.cwd is not a function. (In 'process.cwd()', 'process.cwd' is undefined)

### ISSUE THREAD

**Issue by elmaedesistemas** [coingrig/core#3]
Hi! I have this error, but i dont now why haha, please help me!

Error: Requiring module "node_modules/@coingrig/core/dist/index.js", which threw an exception: TypeError: process.cwd is not a function. (In 'process.cwd()', 'process.cwd' is undefined)

React Native Version: "0.66.2",
React: "17.0.2",
@coingrig/core version: "1.2.0"

**Comment by rvulpescu** [comment]
Hi, at a first glance this looks like a development environment setup issue. `process.cwd` is not used by the library code itself.
Try removing your node_modules folder and reinstall the dependencies. NPM / YARN do have issues from time to time.

Also please provide some additional context on the issue. It seems you are you using the library in a react native project.
React native should add a process.env.NODE_ENV variable but that's it.
